name: client test

on:
  push:
    branches: [deus/test-client]

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v2
        id: root-npm-cache
        with:
          path: 'node_modules'
          key: root-npm-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        id: client-npm-cache
        with:
          path: 'client/node_modules'
          key: client-npm-${{ hashFiles('client/package-lock.json') }}
      - run: npm install & npm install --prefix client & wait
        if: steps.root-npm-cache.outputs.cache-hit != 'true' || steps.client-npm-cache.outputs.cache-hit != 'true'
      - name: lint
        run: npm run lint:fix:client
      - name: generate
        run: npm run generate:client
      - name: typecheck
        run: npm run typecheck:client
      - name: test
        run: npm test:client
      - if: failure()
        run: |
          sed -i '/\.env$/d;/\$\*\.ts$/d;/\*\.css\.d\.ts$/d' .gitignore
          echo "package-lock.json" >> .gitignore
          git rm -r --cached .
          rm -rf .github
          unlink README.md
          git config --global user.name 'github-actions[bot]'
          git config --global user.email '41898282+github-actions[bot]@users.noreply.github.com'
          SHORT_SHA=$(git rev-parse --short HEAD)
          git add .
          git commit -m "copy: $SHORT_SHA"
          git push https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }} HEAD:deus/client-failure-types -f
