name: main test

on:
  push:
    branches: main
  pull_request:
    branches: pull_request

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    if: github.repository == 'deus-app/deus-template' || github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v3
      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: actions/cache@v2
        id: root-npm-cache
        with:
          path: 'node_modules'
          key: root-npm-${{ hashFiles('package-lock.json') }}
      - uses: actions/cache@v2
        id: client-npm-cache
        with:
          path: 'client/node_modules'
          key: client-npm-${{ hashFiles('client/package-lock.json') }}
      - uses: actions/cache@v2
        id: server-npm-cache
        with:
          path: 'server/node_modules'
          key: server-npm-${{ hashFiles('server/package-lock.json') }}
      - run: npm install & npm install --prefix client & npm install --prefix server & wait
        if: steps.root-npm-cache.outputs.cache-hit != 'true' || steps.client-npm-cache.outputs.cache-hit != 'true' || steps.server-npm-cache.outputs.cache-hit != 'true'
      - run: npm run lint
      - run: npm run generate
      - run: npm run typecheck
      - run: |
          cp client/.env.example client/.env
          cp server/.env.example server/.env
          cp docker/dev/.env.example docker/dev/.env
          docker compose up -d
      - run: npm test
